---
driver:
  name: ec2

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: "13.8.5"

verifier:
  name: inspec

platforms:
  - name: centos-7.3
    driver:
      image_id: ami-e1496384
  - name: centos-6.8
    driver:
      image_id: ami-ff48629a

suites:
  - name: dev
    verifier:
      inspec_tests:
        - test/smoke/dev
    run_list:
      - recipe[la_java::default]
    attributes: { 'java': { 'jdk_version': '7' } }
    excludes: centos-6.8
  - name: prod
    verifier:
      inspec_tests:
        - test/smoke/prod
    run_list:
      - recipe[la_java::default]
    atributes: { 'java': { 'jdk_version': '6' } }
    includes: centos-7.3
